// Located in your Vercel project's /api/generate.js (or similar)

export default async function handler(req, res) {
  // Add CORS headers
  // REMOVED: res.setHeader('Access-Control-Allow-Credentials', 'true'); <-- This was the problem line
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET,POST,OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');

  // Handle preflight
  if (req.method === 'OPTIONS') {
    res.status(200).end();
    return;
  }

  // Only allow POST
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  try {
    const { date, userId } = req.body;
    
    // Your content generation logic here
    const data = {
      research: {
        title: "The Power of Deliberate Practice",
        introduction: "An exploration into the principles of deliberate practice and its impact on skill acquisition.",
        keyFindings: "Consistent, focused effort on specific sub-skills, combined with immediate feedback, leads to significantly faster improvement than simple repetition.",
        conclusion: "Mastery is not an innate talent but a product of structured and intentional practice over time.",
        source: "Generated by Inner Lab API"
      },
      concepts: [
        { term: "Neuroplasticity", definition: "The brain's ability to reorganize itself by forming new neural connections throughout life." },
        { term: "Growth Mindset", definition: "The belief that one's abilities and intelligence can be developed through dedication and hard work." }
      ]
    };

    res.status(200).json(data);
  } catch (error) {
    console.error('API Error:', error);
    res.status(500).json({ 
      error: 'Failed to generate content',
      details: error.message 
    });
  }
}
